dist: trusty
sudo: required
os:
  - linux
  - osx
language:
  - cpp
compiler:
  - gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-9
      - g++-9
      - cmake
      - rpm
install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ] && [ "$CXX" = "g++" ]; then export CXX="g++-9" CC="gcc-9"; fi
before_script:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then ./build.linux.bsh; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ];   then ./build.xcode.bsh; fi
script:
  - gcc -v && g++ -v && cmake --version
  - cd build
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then make; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ];   then xcodebuild -configuration Release; fi
  - ctest -C Release
  - cpack
  - cd ..
deploy:
  provider: releases
  api_key: "$GITHUB_API_KEY"
  file_glob: true
  file: 
   - "build/libict-*.tar.Z"
   - "build/libict-*.tar.gz"
   - "build/libict-*.sh"
   - "build/libict-*.deb"
   - "build/libict-*.rpm"
  skip_cleanup: true
  on:
    tags: true
